### ISSUE TITLE
Question: possibility of making a tag like NTAG213 specific to a user, except for making it read-only

### ISSUE THREAD

**Issue by makhosravi** [okadan/flutter-nfc-manager#59] opened 2021-08-04 06:51 UTC
Hi

I have a question.
Is it possible to make a tag password protected (if possible on a tag like NTAG213), so the tag becomes personal to a specific user, with this package? or is there any other way to make a tag specific to a user?
Hope to hear soon from you.

Thank you

**Comment by okadan** [comment] 2021-08-05 06:53
Duplicate of #20

**Comment by makhosravi** [comment] 2021-08-05 09:18
Thank you

**Closed as completed** 2021-08-05 09:37 UTC
